- name: install nginx
  become_user: root
  apt:
    name: nginx-extras

- name: Allow Nginx
  become_user: root
  ufw:
    rule: allow
    name: Nginx Full

- name: Monitoring
  import_tasks: monitoring.yml
