[tool.poetry]
name = "lesswrong-ru-deploy"
version = "0.2.0"
description = ""
authors = ["Vyacheslav Matyukhin <me@berekuk.ru>"]

[tool.poetry.dependencies]
python = "^3.7"

ansible = "^2.8"

jinja2 = "*"
PyYAML = "*"
cryptography = "*"
