- hosts: production
  roles:
    - lw # we need to create the lw user first

- hosts: production
  become_user: lw
  become: yes

  roles:
    - { role: nginx, tags: nginx }
    - { role: clippy, tags: clippy }
    - { role: wiki, tags: wiki }
    - { role: website, tags: website }
    - { role: lw-cert, tags: cert }

- hosts: slack
  become_user: berekuk
  become: yes

  roles:
    - { role: slack-search, tags: slack }

- hosts: next
  roles:
    - lw # we need to create the lw user first

- hosts: kocherga_prometheus
  name: Gather facts from kocherga_prometheus
  tasks: [ ]

- hosts: next
  become_user: lw
  become: yes

  roles:
    - { role: firewall, tags: firewall }
    - { role: docker, tags: docker }
    - { role: node_exporter, tags: node_exporter }
