- hosts: production
  roles:
    - lw # we need to create the lw user first

- hosts: production
  become_user: lw
  become: yes

  roles:
    - { role: nginx, tags: nginx }
    - { role: clippy, tags: clippy }
    - { role: wiki, tags: wiki }

- hosts: slack
  become_user: berekuk
  become: yes

  roles:
    - { role: slack-search, tags: slack }
