- name: Logging directories
  become_user: root
  file:
    name: "{{item}}"
    owner: lw
    group: lw
    state: directory
    mode: 0770
  with_items:
    - "{{lw.clippy.data}}"

- name: Fetch code
  git:
    repo: "{{lw.clippy.repo}}"
    dest: "{{lw.clippy.srv}}"
    accept_hostkey: yes
  notify:
    - restart app

- name: Add env config
  template:
    src: env
    dest: "{{lw.clippy.srv}}/env"
  notify:
    - restart app

- name: Set up a pipenv environment
  include_role:
    name: pipenv
  vars:
    dir: "{{lw.clippy.srv}}"
  notify: restart app

- name: Install systemd config
  include_role:
    name: service
  vars:
    template: systemd
    service: clippy
  notify:
    - restart app

- name: Install nginx config
  include_role:
    name: nginx-site
  vars:
    nginx_template: nginx
    nginx_site: "{{lw.clippy.domain}}"
