<?php
# This file was automatically generated by the MediaWiki 1.28.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

setlocale( LC_ALL, "en_US.UTF-8" );

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Вики LessWrong.ru";
$wgMetaNamespace = "Meta";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/wiki";
$wgArticlePath = "$wgScriptPath/$1";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://lesswrong.ru";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/lw.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "lw@lesswrong.ru";
$wgPasswordSender = "lw@lesswrong.ru";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wiki";
$wgDBuser = "wiki";
$wgDBpassword = "{{lw.wiki.db.password}}";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_MEMCACHED;
$wgParserCacheType = CACHE_MEMCACHED;
$wgMessageCacheType = CACHE_MEMCACHED;
$wgSessionsInObjectCache = true;
$wgSessionCacheType = CACHE_MEMCACHED;
$wgMemCachedServers = [ '127.0.0.1:11211' ];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "ru";

$wgSecretKey = "{{lw.wiki.secret_key}}";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "6170e749c16f50a4";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
#$wgRightsPage = "Meta:Copyright"; # Set to the title of a wiki page that describes your license/copyright
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/3.0/deed.ru";
$wgRightsText = "CC-BY-SA-3.0";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/CC-BY-SA-3.0.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# End of automatically generated settings.
# Add more configuration options below.

# Enabled skins.
wfLoadSkin( 'Vector' );
wfLoadSkin('MinervaNeue');

$wgRestrictDisplayTitle = false;
$wgAllowDisplayTitle = true;

$wgFileExtensions[] = 'pdf';

# ===== Extensions =====

wfLoadExtension('Math');
$wgDefaultUserOptions['math'] = 'mathml';
$wgMathFullRestbaseURL = 'https://en.wikipedia.org/api/rest_'; # don't forget to install php-curl

wfLoadExtension('WikiEditor');
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;

wfLoadExtension('Cite');
wfLoadExtension('Interwiki');
$wgGroupPermissions['sysop']['interwiki'] = true;

wfLoadExtension('ParserFunctions');

wfLoadExtension('NewestPages');

wfLoadExtension('EmbedVideo');

wfLoadExtension('MultimediaViewer');

wfLoadExtension('CategoryTree');

wfLoadExtension('EditAccount');

wfLoadExtension('SlackNotifications');
$wgSlackIncomingWebhookUrl = "{{lw.wiki.extensions.slack_notifications.webhook}}";
$wgSlackFromName = "Wiki";
$wgWikiUrl      = "https://lesswrong.ru/wiki/";
$wgWikiUrlEnding = "index.php?title=";
$wgSlackSendMethod = "curl";
$wgSlackIgnoreMinor = true;
$wgSlackExcludeNotificationsFrom = ["Участник:"];

define('NS_MEETUP', 3000);
define('NS_MEETUP_TALK', 3001);

$wgExtraNamespaces[NS_MEETUP] = "Встреча";
$wgExtraNamespaces[NS_MEETUP_TALK] = "Обсуждение_встречи"; // Note underscores in the namespace name.

$wgAllowExternalImagesFrom = ['https://emoji.slack-edge.com'];

wfLoadExtension('MsUpload');

wfLoadExtension('ReplaceText');

enableSemantics('lesswrong.ru');

$smwgMainCacheType = CACHE_MEMCACHED;

$smwgNamespacesWithSemanticLinks[NS_MEETUP] = true;
$smwgNamespacesWithSemanticLinks[NS_TEMPLATE] = true;

$smwgShowFactbox = SMW_FACTBOX_NONEMPTY;

$smwgPageSpecialProperties = ['_MDAT', '_CDAT'];
// SMWResultPrinter::$maxRecursionDepth = 4;

wfLoadExtension('PageForms');

wfLoadExtension( 'MobileFrontend' );
$wgMFAutodetectMobileView = true;
$wgMFDefaultSkinClass = 'SkinMinerva';
