- name: install certbot-auto
  become_user: root
  get_url:
    url: https://dl.eff.org/certbot-auto
    mode: 0700
    owner: root
    group: root
    dest: /srv/certbot-auto

- name: install route53 plugin
  become_user: root
  pip:
    name: certbot-dns-route53
    virtualenv: /opt/eff.org/certbot/venv

- name: install aws credentials
  become_user: root
  template:
    src: aws.config
    dest: /srv/certbot.aws.config

- name: get certificates
  when: certbot_domain_configured.stat.exists == False
  become_user: root
  command: /srv/certbot-auto certonly -n -d {{ domains|join(' -d ') }} --cert-name {{certname}} --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory --email {{certbot.email}} --dns-route53 --post-hook "service nginx restart"
  environment:
    AWS_CONFIG_FILE: /srv/certbot.aws.config
