- name: install certbot-auto
  become_user: root
  get_url:
    url: https://dl.eff.org/certbot-auto
    mode: 0700
    owner: root
    group: root
    dest: /srv/certbot-auto

- name: install route53 plugin
  become_user: root
  pip:
    name: certbot-dns-route53
    virtualenv: /opt/eff.org/certbot/venv

- name: install aws credentials
  become_user: root
  template:
    src: aws.config
    dest: /srv/certbot.aws.config

# TODO: get certificates, install renew cron script
# /srv/certbot-auto certonly -d '*.lesswrong.ru' -d 'lesswrong.ru' --preferred-challenges dns-01 --server https://acme-v02.api.letsencrypt.org/directory --email me@berekuk.ru --dns-route53
